ENH: Draft JOSS paper
enthought/vpsearch pull request #17
Opened 2022-01-03 09:00 UTC by jvkersch

Happy new year!

This is a draft for a [JOSS](https://joss.theoj.org/) submission﻿about vpsearch. I think it is submission ready, modulo perhaps some tweaks.

You can get a preview of what the paper will look like at https://whedon.theoj.org/.

2022-01-06 19:16 UTC, stevenjkern requested changes
Looks lovely, @jvkersch! I have just a few very small comments. 🙏🏻 ❤️

2022-01-08 11:45 UTC, jvkersch commented on paper/paper.md
> +The VPsearch tool is implemented in Python, using Cython for
Good idea. There's an [IEEE paper ](https://ieeexplore.ieee.org/document/5582062)(from 2011) that is mentioned on the Cython homepage, I'll add that.

2022-01-08 11:48 UTC, jvkersch commented
@stevenjkern Thanks for picking up on this and for the quick turnaround in reviewing. I was going to send you an email about this, but you saw the PR before I had done so.

I think I've addressed your comments, let me know if this looks good. If you approve of the PR, I'll take that as a sign that the paper is ready for submission to JOSS.

2022-01-11 01:05 UTC, stevenjkern commented on paper/paper.bib
> +  journal={Computing in Science   Engineering},
```suggestion
  journal={Computing in Science \& Engineering},
```

2022-01-11 01:06 UTC, stevenjkern approved these changes
LGTM modulo missing &

:shipit:

2022-01-11 07:34 UTC, jvkersch commented
Thanks @stevenjkern, good catch! I'll merge the PR now and submit off the draft, and we can open separate PRs for follow-up changes.

2022-01-11 07:34 UTC, merged